In [1]:
import bonhomme_manresa

In [2]:
from linearmodels.datasets import wage_panel

wage_panel_df = wage_panel.load()

wage_panel_df.set_index(["nr", "year"], inplace=True)
y = wage_panel_df["lwage"]
x = wage_panel_df.drop(columns=["occupation", "lwage"])
display(x)
display(y)

black  exper  hisp  hours  married  educ  union  expersq
nr    year                                                          
13    1980      0      1     0   2672        0    14      0        1
      1981      0      2     0   2320        0    14      1        4
      1982      0      3     0   2940        0    14      0        9
      1983      0      4     0   2960        0    14      0       16
      1984      0      5     0   3071        0    14      0       25
...           ...    ...   ...    ...      ...   ...    ...      ...
12548 1983      0      8     0   2080        1     9      0       64
      1984      0      9     0   2080        1     9      1       81
      1985      0     10     0   2080        1     9      0      100
      1986      0     11     0   2080        1     9      1      121
      1987      0     12     0   3380        1     9      1      144

[4360 rows x 8 columns]

nr     year
13     1980    1.197540
       1981    1.853060
       1982    1.344462
       1983    1.433213
       1984    1.568125
                 ...   
12548  1983    1.591879
       1984    1.212543
       1985    1.765962
       1986    1.745894
       1987    1.466543
Name: lwage, Length: 4360, dtype: float64

In [3]:
N = x.index.get_level_values(0).nunique()
T = x.index.get_level_values(1).nunique()
K = x.shape[1]
x = x.values.reshape(N, T, K).astype(float)
y = y.values.reshape(N, T, 1).astype(float)
x, y

(array([[[  0.,   1.,   0., ...,  14.,   0.,   1.],
         [  0.,   2.,   0., ...,  14.,   1.,   4.],
         [  0.,   3.,   0., ...,  14.,   0.,   9.],
         ...,
         [  0.,   6.,   0., ...,  14.,   0.,  36.],
         [  0.,   7.,   0., ...,  14.,   0.,  49.],
         [  0.,   8.,   0., ...,  14.,   0.,  64.]],
 
        [[  0.,   4.,   0., ...,  13.,   0.,  16.],
         [  0.,   5.,   0., ...,  13.,   0.,  25.],
         [  0.,   6.,   0., ...,  13.,   0.,  36.],
         ...,
         [  0.,   9.,   0., ...,  13.,   0.,  81.],
         [  0.,  10.,   0., ...,  13.,   0., 100.],
         [  0.,  11.,   0., ...,  13.,   0., 121.]],
 
        [[  0.,   4.,   0., ...,  12.,   0.,  16.],
         [  0.,   5.,   0., ...,  12.,   0.,  25.],
         [  0.,   6.,   0., ...,  12.,   0.,  36.],
         ...,
         [  0.,   9.,   0., ...,  12.,   0.,  81.],
         [  0.,  10.,   0., ...,  12.,   0., 100.],
         [  0.,  11.,   0., ...,  12.,   0., 121.]],
 
        ...,


In [5]:
bonhomme_manresa.grouped_fixed_effects(y, x, 3, max_iter=10000, tol=1e-8, gfe_iterations=100)

(array([[-1.45436897e-01],
        [ 8.93663436e-02],
        [ 3.17180707e-02],
        [-1.01771656e-04],
        [ 8.51561294e-02],
        [ 9.24946024e-02],
        [ 1.02708229e-01],
        [-4.71926501e-03]]),
 array([[-0.12141014, -0.13875472, -0.09234418, -0.09226307, -0.08622614,
         -0.08175309,  0.01889703,  0.11177414],
        [ 0.61077638,  0.71824735,  0.7778693 ,  0.7830138 ,  0.83835341,
          0.87237502,  0.90503412,  0.90803539],
        [ 0.25507638,  0.34164758,  0.30020873,  0.32778398,  0.3847847 ,
          0.43109681,  0.4694478 ,  0.55359295]]),
 array([0, 2, 1, 2, 1, 2, 1, 0, 2, 2, 0, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1,
        1, 1, 0, 2, 1, 2, 0, 1, 2, 1, 1, 0, 1, 2, 2, 2, 1, 2, 0, 0, 2, 2,
        1, 2, 0, 1, 0, 1, 2, 0, 1, 0, 2, 0, 0, 1, 1, 0, 0, 1, 2, 1, 2, 2,
        0, 2, 0, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 0, 0, 0, 0,
        2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 2, 2,
        2, 2, 2, 0, 1, 2, 2, 2, 2, 1, 2, 